baseURL = 'https://fernandosouza.dev/'
languageCode = 'en-us'
title = 'Fernando Souza'
theme = "PaperMod"

# [menus]
#   [[menus.main]]
#     name = 'Home'
#     pageRef = '/'
#     weight = 10
#   [[menus.main]]
#     name = 'Contact'
#     pageRef = '/contact'
#     weight = 30

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light
  [profileMode]
    enabled = true

  # home page profile
  avatar = 'nandosouzafilho@gmail.com'                 # gravatar email or image url
